### PR TITLE
Update inheritance.md

### PR DESCRIPTION
**Pull request by leandroborgesca**

### CODE REVIEW

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/tutorials/inheritance.md](https://github.com/leandroborgesca/docs.pt-br/blob/patch-2/docs/csharp/tutorials/inheritance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/pt-br/dotnet/csharp/tutorials/inheritance?branch=pr-pt-br-21) | [Details](#user-content-docs%2Fcsharp%2Ftutorials%2Finheritance.md)

<a name="docs%2Fcsharp%2Ftutorials%2Finheritance.md"></a>
### [docs/csharp/tutorials/inheritance.md](https://github.com/leandroborgesca/docs.pt-br/blob/patch-2/docs/csharp/tutorials/inheritance.md)
 - **[Warning]** Invalid cross reference &quot;&amp;lt;xref:System.Object&amp;gt;&quot;, &quot;&amp;lt;xref:System.Type&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.Finalize%2A&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.MemberwiseClone%2A&amp;gt;&quot;, &quot;&amp;lt;xref:System.ValueType&amp;gt;&quot;, &quot;&amp;lt;xref:System.Enum&amp;gt;&quot;, &quot;&amp;lt;xref:System.MulticastDelegate&amp;gt;&quot;, &quot;&amp;lt;xref:System.Delegate&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.ToString%2A?displayProperty=fullName&amp;gt;&quot;, &quot;&amp;lt;xref:System.MemberAccessException&amp;gt;&quot;, &quot;&amp;lt;xref:System.String&amp;gt;&quot;, &quot;&amp;lt;xref:System.Int32&amp;gt;&quot;, &quot;&amp;lt;xref:System.ArgumentOutOfRangeException&amp;gt;&quot;, &quot;&amp;lt;xref:System.Globalization.RegionInfo.ISOCurrencySymbol%2A&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.Equals%28System.Object%29?displayProperty=fullName&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.GetHashCode%2A&amp;gt;&quot;, &quot;&amp;lt;xref:System.String.GetHashCode%2A&amp;gt;&quot;.
 - **Line 244**: **[Warning]** Invalid file link:(~/docs/csharp/tutorials/media/publication-class.jpg).
 - **Line 278**: **[Warning]** Invalid file link:(~/docs/csharp/tutorials/media/book-class.jpg).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C14%5Cb8b4e7e1-10d5-1ca9-eaef-eeb830e2312d%5CPullRequest%5C201708141617416333-21%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Hi @leandroborgesca , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @leandroborgesca , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @leandroborgesca , we are still in discussing, will update the decision later soon.

Your contribution has been already escalated to the Article writer:
https://github.com/dotnet/docs/pull/2931 

Thanks for your support,

Microsoft C&E Localization Team

**Comment by gosali** [comment]
@leandroborgesca,  Thank you for your feedback and suggestion! 
  
 We found that your change would still be wrong, 'Title' is a get-only auto-property, it doesn't have a named backing field. So We think the whole "which stores the value in a private field named pubTitle" part should be removed. 
This is not fully aligned to our acceptance criterial, I am closing this PR. 
  
Microsoft C&E Localization Team

**Comment by mairaw** [comment]
Obrigada @leandroborgesca pela sua sugestão. Na verdade, um dos nossos contribuintes acabou arrumando o tópico em inglês com o PR https://github.com/dotnet/docs/pull/2933 e assim que o tópico for traduzido novamente, o erro vai ser consertado em português também. 

Sempre que você ver um erro no tópico que não seja problema de tradução, mas um erro no tópico em si, o problema vai ser primeiramente arrumado no conteúdo original (em inglês). 

Mas obrigada pelas suas sugestões! Estamos melhorando a qualidade do nosso conteúdo com elas.

**Pull request closed without merging**
