### PR TITLE
Update inheritance.md

### PR DESCRIPTION
**Pull request by leandroborgesca**
Não existe o campo id na classe Book

### CODE REVIEW

**Comment by olprod** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/tutorials/inheritance.md](https://github.com/leandroborgesca/docs.pt-br/blob/patch-4/docs/csharp/tutorials/inheritance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/pt-br/dotnet/csharp/tutorials/inheritance?branch=pr-pt-br-23) | [Details](#user-content-docs%2Fcsharp%2Ftutorials%2Finheritance.md)

<a name="docs%2Fcsharp%2Ftutorials%2Finheritance.md"></a>
### [docs/csharp/tutorials/inheritance.md](https://github.com/leandroborgesca/docs.pt-br/blob/patch-4/docs/csharp/tutorials/inheritance.md)
 - **[Warning]** Invalid cross reference &quot;&amp;lt;xref:System.Object&amp;gt;&quot;, &quot;&amp;lt;xref:System.Type&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.Finalize%2A&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.MemberwiseClone%2A&amp;gt;&quot;, &quot;&amp;lt;xref:System.ValueType&amp;gt;&quot;, &quot;&amp;lt;xref:System.Enum&amp;gt;&quot;, &quot;&amp;lt;xref:System.MulticastDelegate&amp;gt;&quot;, &quot;&amp;lt;xref:System.Delegate&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.ToString%2A?displayProperty=fullName&amp;gt;&quot;, &quot;&amp;lt;xref:System.MemberAccessException&amp;gt;&quot;, &quot;&amp;lt;xref:System.String&amp;gt;&quot;, &quot;&amp;lt;xref:System.Int32&amp;gt;&quot;, &quot;&amp;lt;xref:System.ArgumentOutOfRangeException&amp;gt;&quot;, &quot;&amp;lt;xref:System.Globalization.RegionInfo.ISOCurrencySymbol%2A&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.Equals%28System.Object%29?displayProperty=fullName&amp;gt;&quot;, &quot;&amp;lt;xref:System.Object.GetHashCode%2A&amp;gt;&quot;, &quot;&amp;lt;xref:System.String.GetHashCode%2A&amp;gt;&quot;.
 - **Line 244**: **[Warning]** Invalid file link:(~/docs/csharp/tutorials/media/publication-class.jpg).
 - **Line 278**: **[Warning]** Invalid file link:(~/docs/csharp/tutorials/media/book-class.jpg).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C14%5Cb8b4e7e1-10d5-1ca9-eaef-eeb830e2312d%5CPullRequest%5C201708141655321647-23%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by gosali** [comment]
Olá @leandroborgesca , ainda estamos analisando. Atualizaremos a decisão mais tarde.  
  
Obrigado por seu suporte, 
Equipe de Localização C&E da Microsoft

**Comment by v-radelg** [comment]
Olá @leandroborgesca , agradecemos seus comentários e sugestões!   	  	
Encontramos <motivos GERAIS>, que não está totalmente alinhado com nosso critério de aceitação. Eu estou fechando esse PR. Fique à vontade para reabrir o PR se você precisar de mais análise.   	  
Equipe de Localização C&E da Microsoft

**Comment by mairaw** [comment]
Oi @leandroborgesca, obrigada pela sugestão. Eu reviseu seu pedido e criei um PR para arrumar o tópico em inglês primeiro e aí as versões localizadas serão atualizadas posteriormente.
Você poder ver a PR aqui: https://github.com/dotnet/docs.pt-br/pull/23

**Pull request closed without merging**
