### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by thild**
Corrected some translation issues. Some technical words are common and better understood in English, so they were kept without translation.

### CODE REVIEW

**Comment by olprod** [comment]
### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events.md) | :x:Error | [View](https://review.docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events?branch=pr-pt-br-20) | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fevents%2Fhow-to-subscribe-to-and-unsubscribe-from-events.md)
[docs/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md) | :x:Error | [View](https://review.docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception?branch=pr-pt-br-20) | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fexceptions%2Fhow-to-catch-a-non-cls-exception.md)
[docs/core/index.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/core/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/pt-br/dotnet/core/index?branch=pr-pt-br-20) | [Details](#user-content-docs%2Fcore%2Findex.md)

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fevents%2Fhow-to-subscribe-to-and-unsubscribe-from-events.md"></a>
### [docs/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[csprcs](../../../csharp/includes/csprcs_md.md)]&quot; at line 49: Couldn&#39;t find file docs/csharp/includes/csprcs_md.md. Fallback folders: W:\jkcc-s\_repo.en-us\.

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fexceptions%2Fhow-to-catch-a-non-cls-exception.md"></a>
### [docs/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[csprcs](../../../csharp/includes/csprcs_md.md)]&quot; at line 37: Couldn&#39;t find file docs/csharp/includes/csprcs_md.md. Fallback folders: W:\jkcc-s\_repo.en-us\.
 - **[Error]** Unable to resolve &quot;[!INCLUDE[csprcs](../../../csharp/includes/csprcs_md.md)]&quot; at line 41: Couldn&#39;t find file docs/csharp/includes/csprcs_md.md. Fallback folders: W:\jkcc-s\_repo.en-us\.
 - **[Error]** Unable to resolve &quot;[!INCLUDE[csprcs](../../../csharp/includes/csprcs_md.md)]&quot; at line 54: Couldn&#39;t find file docs/csharp/includes/csprcs_md.md. Fallback folders: W:\jkcc-s\_repo.en-us\.

<a name="docs%2Fcore%2Findex.md"></a>
### [docs/core/index.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/core/index.md)
 - **Line 116**: **[Warning]** Invalid file link:(~/docs/images/corefx-platforms-loc.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C8%5Cb8b4e7e1-10d5-1ca9-eaef-eeb830e2312d%5CPullRequest%5C201708080349398388-20%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
Hi @thild , we are still in discussing, will update the decision later soon. 
		
Thanks for your support,

Microsoft C&E Localization Team

**Comment by olprod** [comment]
### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md) | :x:Error | [View](https://review.docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception?branch=pr-pt-br-20) | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fexceptions%2Fhow-to-catch-a-non-cls-exception.md)
[docs/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events.md) | :x:Error | [View](https://review.docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events?branch=pr-pt-br-20) | [Details](#user-content-docs%2Fcsharp%2Fprogramming-guide%2Fevents%2Fhow-to-subscribe-to-and-unsubscribe-from-events.md)
[docs/core/index.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/core/index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/pt-br/dotnet/core/index?branch=pr-pt-br-20) | [Details](#user-content-docs%2Fcore%2Findex.md)

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fexceptions%2Fhow-to-catch-a-non-cls-exception.md"></a>
### [docs/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/csharp/programming-guide/exceptions/how-to-catch-a-non-cls-exception.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[csprcs](../../../csharp/includes/csprcs_md.md)]&quot; at line 37: Couldn&#39;t find file docs/csharp/includes/csprcs_md.md. Fallback folders: W:\jkcc-s\_repo.en-us\.
 - **[Error]** Unable to resolve &quot;[!INCLUDE[csprcs](../../../csharp/includes/csprcs_md.md)]&quot; at line 41: Couldn&#39;t find file docs/csharp/includes/csprcs_md.md. Fallback folders: W:\jkcc-s\_repo.en-us\.
 - **[Error]** Unable to resolve &quot;[!INCLUDE[csprcs](../../../csharp/includes/csprcs_md.md)]&quot; at line 54: Couldn&#39;t find file docs/csharp/includes/csprcs_md.md. Fallback folders: W:\jkcc-s\_repo.en-us\.

<a name="docs%2Fcsharp%2Fprogramming-guide%2Fevents%2Fhow-to-subscribe-to-and-unsubscribe-from-events.md"></a>
### [docs/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events.md)
 - **[Error]** Unable to resolve &quot;[!INCLUDE[csprcs](../../../csharp/includes/csprcs_md.md)]&quot; at line 49: Couldn&#39;t find file docs/csharp/includes/csprcs_md.md. Fallback folders: W:\jkcc-s\_repo.en-us\.

<a name="docs%2Fcore%2Findex.md"></a>
### [docs/core/index.md](https://github.com/thild/docs.pt-br/blob/patch-2/docs/core/index.md)
 - **Line 116**: **[Warning]** Invalid file link:(~/docs/images/corefx-platforms-loc.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C10%5Cb8b4e7e1-10d5-1ca9-eaef-eeb830e2312d%5CPullRequest%5C201708101246035940-20%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-radelg** [comment]
@thild : Thank you for your feedback and suggestion! 

The feedback is considered. We will tune part of  your feedback in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
		
Microsoft C&E Localization Team

**Pull request merged**
